### ISSUE TITLE
Call for Testers of v1.0.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfaction#1349]
We are planning to release v1.0.0, and we'd like to test it using prerelease versions before releasing it.

- https://github.com/suzuki-shunsuke/tfaction/pull/1291
- https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.0.0-1
- https://github.com/suzuki-shunsuke/tfaction-example/pull/2145
- https://github.com/suzuki-shunsuke/tfaction-example/tree/example-v1-2

Please read the release note for the detail.

This release includes several breaking changes, so please follow the upgrade guide.
We tested the prerelease version in our test environment, but we'd like to test it in production environments too.

So we really appreciate it if you try the prerelease version in your production environment.
If you have any troubles or feedbacks, please let us know.
Of course we can help you if you have any troubles.
We can collaborate in private channels if necessary.

Please post comments if you can help us!

Thank you!

## What to do

1. Read the release note https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.0.0-1
1. Upgrade tfaction according to the release note
1. Give us your feedback on this issue

**Comment by rrreeeyyy** [comment]
Hello again, this is @rrreeeyyy from Topotal, Inc.

I've just upgraded our internal environment's tfaction to v1.0.0-1.
We had already completed the transition from tfsec to trivy a while back, and had also made changes related to `terraform_targets` / `tfmigrate_targets` during the upgrade to 0.7.3.
Since we don't use the scaffold-module at our company, we've essentially only made changes related to the `github_token`.

So far, the plan and apply seem to be working correctly, but if any issues arise, I'll leave another comment on this Issue.

**Comment by rrreeeyyy** [comment]
I have a question. I saw that trivy, not tfsec, has become the default tool, so I removed the following lines from tfaction-root:

```yaml
tfsec: 
    enabled: false
trivy:
    enabled: true
```

As a result, after the trivy config command was executed, tfsec started running unexpectedly. Since tfsec was already uninstalled, the workflow stopped with the error `Unable to locate executable file: tfsec.`

I suspect this is because I'm using target-config, and while in v1.0.0 the default behavior has changed in global-config, it seems that the default behavior in target-config has not been altered.

get-target-config: https://github.com/suzuki-shunsuke/tfaction/blob/e14be0997deaf47227d65f02dcff960fd1dcc862/get-target-config/src/index.ts#L36-L38
get-global-config: https://github.com/suzuki-shunsuke/tfaction/blob/e14be0997deaf47227d65f02dcff960fd1dcc862/get-global-config/src/index.ts#L58-L60

Is this behavior intentional?

**Comment by suzuki-shunsuke** [comment]
Thank you for your cooperation!
Oh, this is a bug.
I've fixed this 5c46bf6d1617a8ac4eae6c1052646cfcb7a8ec8f and released [v1.0.0-2](https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.0.0-2).

**Comment by rrreeeyyy** [comment]
Thank you. I have upgraded to 1.0.0-2 and removed the tfsec and trivy settings from tfaction-root. As intended, `trivy config` was executed, and `tfsec` did not run, which I have confirmed!

**Comment by suzuki-shunsuke** [comment]
Thank you always.
I'm planning to release v1.0.0 on the next Monday if there is no trouble.
I can't release v1 this week because I'm a little busy.

**Comment by suzuki-shunsuke** [comment]
v1 is out 🎉
Thank you for your cooperation!
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v1.0.0
