### ISSUE TITLE
Prevent errors acquiring the state lock after auto updating PR

### ISSUE THREAD

**Issue by tk3fftk** [suzuki-shunsuke/tfaction#803]
**What happened**:
tfaction updates related branches after running `terraform apply`. It's looks good feature but it's not working as desirable when the state lock is enabled and 2 or more pull requests are open. Updated branch's workflows of GitHub Actions are running at the same time and failed due to `Error acquiring the state lock` except one workflow.

**What you expected to happen**:
- Retry unitl the state lock is released or an attempt limit is exceeded
- Simply add option to skip auto updating PRs feature
  - A workaround is using [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency).

**How to reproduce it**:
- Enable terraform state lock feature
- Open 3 or more pull requests which runs `terraform plan`
- Merge a pull request and trigger `terraform apply` and auto updating PRs
- `Error acquiring the state lock` may be caused

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
I understood the issue.

> Retry unitl the state lock is released or an attempt limit is exceeded

I found an issue, but this has been left for a long time.

- https://github.com/hashicorp/terraform/issues/21829

One idea is that tfaction retries `terraform plan` if the error occurs.
This is a bit complicated because we have to output the result of `terraform plan` to text files temporarily to notify the result by tfcmt.

> Simply add option to skip auto updating PRs feature

This approach has an issue that plan file keeps stale.

Third idea is to retry workflow manually.

**Comment by tk3fftk** [comment]
Thank you for your replying:pray:

> One idea is that tfaction retries terraform plan if the error occurs.
This is a bit complicated because we have to output the result of terraform plan to text files temporarily to notify the result by tfcmt.

Make sense it's a bit complicated.

> This approach has an issue that plan file keeps stale.

So skip approach is just an option. Users can select updating PRs or not. Default behavior is updating PRs after `terraform apply`.

> Third idea is to retry workflow manually.

We have to do this in the situation. But failure worflows and comments are noisy and waste😥

**Comment by suzuki-shunsuke** [comment]
# Idea 4. Add an option to skip updating pull requests

If this option is false by default.
If this option is true, tfaction skips updating pull requests.
We would be able to implement this easily.

I dislike this idea because probably users would merge pull requests without rerunning `terraform plan`, and `terraform apply` would fail.

# Idea 5. Add an option to update at most one pr

If this option is false by default.
If this option is true, tfaction updates at most one pr.
If there two or more prs, tfaction updates only one pr and posts the following comments to other prs.

```
# ⚠️ Remote state was updated. Please rerun `terraform plan` to update a plan file

Remote state was updated by #<pr number>, so this pull request's plan file became stale.
Please rerun `terraform plan` to update a plan file, otherwise `terraform apply` would fail.
For the detail, please see <link to the document of tfaction>.
```

~~The pull request comment is user friendly, but maybe you feel noisy. 🤔~~

tfaction-root.yaml

```yaml
update_only_one_pr: true
```

**Comment by suzuki-shunsuke** [comment]
Implemented `Idea 5`.

- https://github.com/suzuki-shunsuke/tfaction/pull/806

You can try the development version `suzuki-shunsuke/tfaction/*@pr/806`.

**Comment by suzuki-shunsuke** [comment]
📝 terragrunt supports retry.

- https://terragrunt.gruntwork.io/docs/features/auto-retry/

**Comment by tk3fftk** [comment]
Thank you for your quick implementation.

I think `update_only_one_pr` feature is look like the same behavior with using `concurrency: ${{matrix.target.target}}` setting in jobs excepting post comments. When `terraform plan` job is skipped by GHA's concurrency setting, PR check is failed by canceled job so users should rerun a plan job.

![image](https://user-images.githubusercontent.com/3445553/225266094-962e3b03-9a30-423a-9770-31c863e91ad9.png)

**Comment by suzuki-shunsuke** [comment]
If you don't want to cancel jobs, how about ~~stop using `concurrency`~~ setting `cancel-in-progress: false`?

**Comment by tk3fftk** [comment]
`cancel-in-progress` is a setting to cancel a running job when a new job is triggerd. `concurrency` would only have a one queue to wait a running job and cancel the queued job when a new job is triggerd in my understanding.

**Comment by suzuki-shunsuke** [comment]
https://docs.github.com/en/actions/using-jobs/using-concurrency#overview

> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.

--

> Any previously pending job or workflow in the concurrency group will be canceled

Oh, I see. I didn't know this.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/issues/892

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.23
You can disable to update related pull requests.
