### ISSUE TITLE
Option to disable updating related pull requests

### ISSUE THREAD

**Issue by johnmanjiro13** [suzuki-shunsuke/tfaction#892]
I use tfaction and it's so useful, thank you for developing!

Now, tfaction always updates related pull requests when the base branch is updated and runs terraform plan.
It consumes free minutes of github actions when  I have some pull requests which I can't merge immediately with some reason.
I won't need always updating because I use branch protection rules to check a branch is updated with the latest changes.
I just merge the base branch as needed.

Therefore, could you add an option to disable automatic updates?

**Comment by suzuki-shunsuke** [comment]
Related.

- https://github.com/suzuki-shunsuke/tfaction/issues/803

**Comment by suzuki-shunsuke** [comment]
https://suzuki-shunsuke.github.io/tfaction/docs/feature/auto-update-related-prs

> By updating pull request branch, the result of CI including uploaded Terraform Plan file is updated.
> Otherwise, an uploaded Terraform Plan file becomes stale and it would fail to run terraform apply.

As described in the document, Terraform Plan file must be updated before merging the pull request.
So if the automatic update of related pull requests is disabled, I have a concern that users forget to update Terraform Plan files and `terraform apply` fails.

In some use case the maintainer of workflow and users of the workflow are different.
Users aren't familiar with tfaction and they don't know that they have to update the plan file.
They can't understand what happens when `terraform apply` fails.

So I disagree to this feature, but I think we can support this feature at user's own risk.

Ideally I'd like to make CI status failure and prevent pull requests from being merged, but it's a bit difficult.

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction/pull/898

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfaction-docs/pull/85

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.5.23

**Comment by johnmanjiro13** [comment]
Thank you for your quick implementation.

>In some use case the maintainer of workflow and users of the workflow are different.
Users aren't familiar with tfaction and they don't know that they have to update the plan file.
They can't understand what happens when terraform apply fails.

That makes sense. I hadn't thought about the possibility of different teams.
I'll use this feature at my risk.
